#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M4F{1,0,7.80,1
#
Morrison.xrm4f: package/cfg/Morrison.xrm4f.mak

clean::
	-$(RM) package/cfg/Morrison.xrm4f.mak
